apiVersion: v2
name: kode
description: A Helm chart for the Kode Operator. It installs the Kode Operator and its dependencies.
type: application
version: "v0.0.0-latest" # This is automatically set by the GitHub Actions workflow
appVersion: "v0.0.0-latest" # This is automatically set by the GitHub Actions workflow
