apiVersion: v2
name: kode
description: A Helm chart for the Kode Operator. It installs the Kode Operator and its dependencies.
type: application
version: "v0.0.0-latest" # This is automatically set by the GitHub Actions workflow
appVersion: "v0.0.0-latest" # This is automatically set by the GitHub Actions workflow
dependencies:
  - name: kode-crd
    version: "v0.0.0-latest" # This is automatically set by the GitHub Actions workflow
    repository: "oci://ghcr.io/jacero-io/charts"
  - name: cert-manager
    repository: https://charts.jetstack.io
    condition: certmanager.enabled
    alias: certmanager
    version: "1.15.2"
