---
apiVersion: kode.jacero.io/v1alpha2
kind: PodTemplate
metadata:
  labels:
    app.kubernetes.io/name: kode-operator
    app.kubernetes.io/managed-by: kustomize
  name: podtemplate-codeserver-sample
  namespace: default
spec:
  type: code-server
  image: linuxserver/code-server:latest
  tz: "Europe/Stockholm"
  puid: 1000
  pgid: 1000
  defaultHome: /config
  defaultWorkspace: workspace
