# permissions for end users to view clusterpodtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kode-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterpodtemplate-viewer-role
rules:
- apiGroups:
  - kode.jacero.io
  resources:
  - clusterpodtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kode.jacero.io
  resources:
  - clusterpodtemplates/status
  verbs:
  - get
