---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kode.jacero.io
  resources:
  - clusterentrypoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kode.jacero.io
  resources:
  - clusterentrypoints/finalizers
  verbs:
  - update
- apiGroups:
  - kode.jacero.io
  resources:
  - clusterentrypoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kode.kode.jacero.io
  resources:
  - clusterpodtemplates
  - clustertofutemplates
  - podtemplates
  - tofutemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kode.kode.jacero.io
  resources:
  - kodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kode.kode.jacero.io
  resources:
  - kodes/finalizers
  verbs:
  - update
- apiGroups:
  - kode.kode.jacero.io
  resources:
  - kodes/status
  verbs:
  - get
  - patch
  - update
