# permissions for end users to edit tofutemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kode-operator
    app.kubernetes.io/managed-by: kustomize
  name: tofutemplate-editor-role
rules:
- apiGroups:
  - kode.jacero.io
  resources:
  - tofutemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kode.jacero.io
  resources:
  - tofutemplates/status
  verbs:
  - get
