---
apiVersion: kode.jacero.io/v1alpha1
kind: KodeClusterTemplate
metadata:
  labels:
    app.kubernetes.io/name: kode-operator
    app.kubernetes.io/managed-by: kustomize
  name: kodeclustertemplate-codeserver-sample
spec:
  runtime: container
  containerSpec:
    type: code-server
    image: linuxserver/code-server:latest
    tz: "Europe/Stockholm"
    puid: 1000
    pgid: 1000
    defaultHome: /config
    defaultWorkspace: workspace
