---
apiVersion: kode.jacero.io/v1alpha1
kind: KodeTemplate
metadata:
  labels:
    app.kubernetes.io/name: kode-operator
    app.kubernetes.io/managed-by: kustomize
  name: kodetemplate-codeserver-sample
  namespace: default
spec:
  envoyConfigRef:
    kind: EnvoyProxyConfig
    name: envoyproxyconfig-sample
    namespace: default
  type: code-server
  image: linuxserver/code-server:latest
  tz: "Europe/Stockholm"
  puid: 1000
  pgid: 1000
  defaultHome: /config
  defaultWorkspace: workspace
