---
apiVersion: kode.jacero.io/v1alpha1
kind: Kode
metadata:
  labels:
    app.kubernetes.io/name: kode-operator
    app.kubernetes.io/managed-by: kustomize
  name: kode-webtop-sample
  namespace: default
spec:
  templateRef:
    kind: KodeTemplate
    name: kodetemplate-webtop-sample
    namespace: default
  username: user1
  password: password1
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
