graph TD
    User[User] -->|Creates/Manages| Kode[Kode CR]
    User[User] -->|Creates/Manages| EntryPoint[EntryPoint CR]
    User[User] -->|Creates/Manages| ContainerTemplate[ContainerTemplate CR]
    User[User] -->|Creates/Manages| VirtualTemplate[VirtualTemplate CR]
    User[User] -->|Creates/Manages| ClusterContainerTemplate[ClusterContainerTemplate CR]
    User[User] -->|Creates/Manages| ClusterVirtualTemplate[ClusterVirtualTemplate CR]

    subgraph "Kode Operator"
        H[Kode Controller] -->|Watches| Kode
        EC[EntryPoint Controller] -->|Watches| EntryPoint
        TM[Template Manager] -->|Fetches| ContainerTemplate
        TM[Template Manager] -->|Fetches| VirtualTemplate
        TM[Template Manager] -->|Fetches| ClusterContainerTemplate
        TM[Template Manager] -->|Fetches| ClusterVirtualTemplate
        RM[Resource Manager] -->|Creates/Updates/Deletes| MR[Managed Resources]
        CM[Cleanup Manager] -->|Initiates Cleanup| MR[Managed Resources]
        Validator[Validator] -->|Validates| L[Managed Resources]
        EM[Event Manager] -->|Records Events| P[Kubernetes Events]

        H[Kode Controller] -->|Uses| TM
        H[Kode Controller] -->|Uses| RM
        H[Kode Controller] -->|Uses| CM
        H[Kode Controller] -->|Uses| Validator
        H[Kode Controller] -->|Uses| EM

        EC[EntryPoint Controller] -->|Uses| TM
        EC[EntryPoint Controller] -->|Uses| RM
        EC[EntryPoint Controller] -->|Uses| CM
        EC[EntryPoint Controller] -->|Uses| Validator
        EC[EntryPoint Controller] -->|Uses| EM
    end

    subgraph "Kubernetes Resources"
        StatefulSet[StatefulSet]
        Service[Service]
        PVC[PersistentVolumeClaim]
        Secret[Secret]
        Gateway[Gateway]
        HTTPRoute[HTTPRoute]
        SecurityPolicy[SecurityPolicy]

        MR --->|Manages| StatefulSet
        MR --->|Manages| Service
        MR --->|Manages| PVC
        MR --->|Manages| Secret
        MR --->|Manages| Gateway
        MR --->|Manages| HTTPRoute
        MR --->|Manages| SecurityPolicy
    end

    subgraph "Envoy Gateway"
        Q[Envoy Gateway] -->|Implements| Gateway
        Q[Envoy Gateway] -->|Implements| HTTPRoute
        Q[Envoy Gateway] -->|Implements| SecurityPolicy
    end