apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kode.fullname" . }}-entrypoint-viewer-role
  labels:
  {{- include "kode.labels" . | nindent 4 }}
rules:
- apiGroups:
  - kode.jacero.io
  resources:
  - entrypoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kode.jacero.io
  resources:
  - entrypoints/status
  verbs:
  - get