apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kode.fullname" . }}-manager-role
  labels:
  {{- include "kode.labels" . | nindent 4 }}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kode.fullname" . }}-manager-role
  labels:
  {{- include "kode.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - event
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kode.jacero.io
  resources:
  - clustercontainertemplates
  - clustertofutemplates
  - containertemplates
  - tofutemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kode.jacero.io
  resources:
  - entrypoints
  - kodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kode.jacero.io
  resources:
  - entrypoints/finalizers
  - kodes/finalizers
  verbs:
  - update
- apiGroups:
  - kode.jacero.io
  resources:
  - entrypoints/status
  - kodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kode.fullname" . }}-manager-rolebinding
  labels:
  {{- include "kode.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kode.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "kode.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'