apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kode.fullname" . }}-manager-role
  labels:
  {{- include "kode.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kode.jacero.io
  resources:
  - entrypoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kode.jacero.io
  resources:
  - entrypoints/finalizers
  verbs:
  - update
- apiGroups:
  - kode.jacero.io
  resources:
  - entrypoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kode.kode.jacero.io
  resources:
  - kodeclustertemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kode.kode.jacero.io
  resources:
  - kodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kode.kode.jacero.io
  resources:
  - kodes/finalizers
  verbs:
  - update
- apiGroups:
  - kode.kode.jacero.io
  resources:
  - kodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kode.kode.jacero.io
  resources:
  - kodetemplates
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kode.fullname" . }}-manager-rolebinding
  labels:
  {{- include "kode.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kode.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "kode.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'