---
apiVersion: kode.jacero.io/v1alpha2
kind: Kode
metadata:
  labels:
    app.kubernetes.io/name: kode-operator
    app.kubernetes.io/managed-by: kustomize
  name: kode-codeserver-sample
  namespace: default
spec:
  credentials:
    username: user1
    password: password1
    enableBuiltinAuth: true
  templateRef:
    kind: ContainerTemplate
    name: containertemplate-codeserver-sample
    namespace: default
  # storage:
  #   existingVolumeClaim: kode1-existing-pvc
  # storage:
  #   accessModes:
  #     - ReadWriteOnce
  #   resources:
  #     requests:
  #       storage: 1Gi
  #   storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kode1-existing-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
