name: Integration Tests

on:
  push:
    branches:
      - main
      - 'feature/*'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

    - name: Set up Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version: '1.22'
        cache-dependency-path: |
          **/go.sum
          **/go.mod

    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: '3.x'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: |
        task tools:setup-github-actions

    - name: Run tests
      env:
        TEST_VERBOSITY: ""
      run: |
        task test:integration
