name: Integration Tests

on:
  push:
    branches:
      - main
      - 'feature/*'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    outputs:
      git_ref: ${{ steps.git_ref.outputs.ref }}
      is_tag: ${{ steps.git_ref.outputs.is_tag }}

    steps:
    - name: Checkout code
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

    - name: Set up Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version: '1.22'
        cache-dependency-path: |
          **/go.sum
          **/go.mod

    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: '3.x'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: |
        task tools:kustomize
        task tools:controller-gen
        task tools:envtest
        task tools:golangci-lint

    - name: Get Git Ref
      id: git_ref
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "ref=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "is_tag=true" >> $GITHUB_OUTPUT
        else
          echo "ref=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          echo "is_tag=false" >> $GITHUB_OUTPUT
        fi
  
    - name: Run tests
      env:
        TEST_VERBOSITY: ""
      run: |
        task test:integration